# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "azurerm" {
    container_name       = "terraform-state-container"
    key                  = "subscriptions/Azure for Students/resource-group/terra-v2/buckets/k8s-ws-bkt/terraform.tfstate"
    resource_group_name  = "terraform-state"
    storage_account_name = "k8sbcstatestorage3"
    subscription_id      = "01b6f96b-3f79-4e73-84de-c180a438d027"
  }
}
